version: '3.8'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "8989:8080" # 로컬 8989 포트로 접속 (8081은 stock-price-service 사용 중)
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-mac
      # 백엔드 카프카 컨테이너망의 내부 리스너 (kafka:9093) 사용
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
    networks:
      - kafka_default

networks:
  kafka_default:
    external: true
