spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

korea-investment-securities:
  app-key: "app-key"
  app-secret: "app-secret"

alpha-vantage:
  api-key: "7HJQWST4SW4DHV9I"
