SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE oauth_credential RESTART IDENTITY;
TRUNCATE TABLE refresh_token RESTART IDENTITY;
TRUNCATE TABLE username_password_credential RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
