SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE stock_entity RESTART IDENTITY;
TRUNCATE TABLE stock_price_entity RESTART IDENTITY;
TRUNCATE TABLE dividend_entity RESTART IDENTITY;
TRUNCATE TABLE income_statement_entity RESTART IDENTITY;
TRUNCATE TABLE member_entity RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
