SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE stock RESTART IDENTITY;
TRUNCATE TABLE income_statement RESTART IDENTITY;
TRUNCATE TABLE favorite_stock RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
