name: api-gateway-service CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - api-gateway-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - working-directory: ${{ github.workspace }}/api-gateway-service
        run: |
          mvn install
          mvn jib:build
  deploy:
    needs: build
    runs-on: [self-hosted, api-gateway-service]
    steps:
      - run: |
          cd /home/ubuntu/pick-and-test-server/api-gateway
          sudo docker compose down api-gateway-service
          sudo docker pull gyeryongbrother/pick-and-test-api-gateway
          sudo docker image prune -f
          sudo docker compose up api-gateway-service -d
