name: member-service CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - member-service/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |
          cd member-service
          mvn install
          mvn jib:build -pl member-container
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - run: |
          aws eks update-kubeconfig --region ap-northeast-2 --name gb
      - run: |
          kubectl rollout restart deployment member-service-deployment
