name: portfolio-service CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - portfolio-service/**
      - .github/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: |
          cd portfolio-service
          mvn install
          mvn jib:build -pl portfolio-container
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - run: |
          cd /home/ubuntu/pick-and-test-server
          sudo docker compose pull portfolio-service
          sudo docker compose up portfolio-service -d
