name: stock-price-service CD

on:
  push:
    branches:
      - main
      - develop
    paths:
      - stock-price-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - working-directory: ${{ github.workspace }}/common
        run: |
          mvn install
      - working-directory: ${{ github.workspace }}/stock-price-service
        run: |
          mvn install
          mvn jib:build -pl stock-price-container
  deploy:
    needs: build
    runs-on: [self-hosted, backend-3]
    steps:
      - run: |
          cd /home/ubuntu/pick-and-test-server/backend-3
          sudo docker compose down stock-price-service
          sudo docker pull gyeryongbrother/pick-and-test-stock-price
          sudo docker image prune -f
          sudo docker compose up stock-price-service -d
